### PR TITLE
Bump out-of-date deps

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

- `predicates = "2.0.1"`
- `pretty_assertions = "0.7"`

```
Crate:         difference
Version:       2.0.0
Warning:       unmaintained
Title:         difference is unmaintained
Date:          2020-12-20
ID:            RUSTSEC-2020-0095
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0095
Dependency tree: 
difference 2.0.0
└── predicates 1.0.8
    └── mockall 0.10.2

```

### CODE REVIEW

**Comment by PsiACE** [comment]
I don't know why the minver test failed.

This problem can only be reproduced in mockall, not in float-cmp.

**Comment by asomers** [comment]
No, the minver failure is real, and it can easily be reproduced in float-cmp alone.

**Comment by PsiACE** [comment]
> No, the minver failure is real, and it can easily be reproduced in float-cmp alone.

Indeed, I found the problem. I ignored the minimum version.

This is obviously an upstream problem, and I will try to solve it.

**Comment by PsiACE** [comment]
cc @asomers , I’m trying to fix this in https://github.com/mikedilger/float-cmp/pull/29 , and I sincerely hope that you can release a preview version first

**Comment by asomers** [comment]
Thanks for going the extra mile to fix float-cmp, @PsiACE .  But why do you want a preview release of Mockall first?  Also, what's wrong with pretty_assertions 0.5?

**Comment by PsiACE** [comment]
> But why do you want a preview release of Mockall first? 

Just my personal suggestion, if you plan to merge this PR. 

> Also, what's wrong with pretty_assertions 0.5?

Newer versions often fix some problems or have better features, and I think it is worth doing this if conditions permit.

**Comment by PsiACE** [comment]
:tada: all ci passed. cc @asomers

**Review by asomers — CHANGES_REQUESTED** [review]
Since Mockall reexports predicates, this constitutes a breaking change.  Would you mind adding an entry to the CHANGELOG?  You don't need to enumerate the full list of predicates' changes; linking to the upstream changelog would suffice.

**Comment by PsiACE** [comment]
> Since Mockall reexports predicates, this constitutes a breaking change. Would you mind adding an entry to the CHANGELOG? You don't need to enumerate the full list of predicates' changes; linking to the upstream changelog would suffice.

Done! Thank you for your review and suggestions.

**Review by asomers — CHANGES_REQUESTED** [review]
Ok, the change looks good.  But would you mind wrapping the CHANGELOG entry to 80 columns and squashing your commits?

**Comment by PsiACE** [comment]
> 
> 
> Ok, the change looks good. But would you mind wrapping the CHANGELOG entry to 80 columns and squashing your commits?

done. but url is too long, I'm so sorry.

**Comment by asomers** [comment]
And how about squashing the changes?

**Comment by PsiACE** [comment]
> And how about squashing the changes?

could you squash and merge? just click the button and select `squash and merge` .

squash

**Comment by asomers** [comment]
Yes, I'm familiar with Github's squash button.  But I use bors on some of my projects, which is not compatible with the squash button.  That's why I usually rely on the submitter to squash.

**Comment by PsiACE** [comment]
> 
> 
> Yes, I'm familiar with Github's squash button. But I use bors on some of my projects, which is not compatible with the squash button. That's why I usually rely on the submitter to squash.

done. i think i learned how to execute squash locally, thanks @asomers

**Comment by asomers** [comment]
Something went wrong when you rebased, because now there's a conflict in CHANGELOG.

**Comment by PsiACE** [comment]
i will close it. and open a new pr.

**Pull request closed without merging**
