### PR TITLE
Fix build when #![deny(missing_docs)] is in force

### PR DESCRIPTION
**Pull request by asomers**
Also, add mor examples to mockall_examples

### CODE REVIEW

**Comment by asomers** [comment]
@codehearts everything should build fine with `#[deny(missing_docs)]` now.  Could you please check it?  I tried to add useful docs everywhere.  But there were a few modules that aren't intended for direct user interaction, yet can't be hidden because they contain things that are intended for user interaction.  For those I simply allowed missing docs.

**Comment by asomers** [comment]
The build failure is due to a stricter check for uninitialized data in the latest nightly compiler.  I'll fix it in a separate PR.

**Comment by codehearts** [comment]
This resolved it for me, thank you so much for making time for this!

**Comment by asomers** [comment]
Thanks for reporting it.  And happy hacking!

**Pull request merged**
