### PR TITLE
Update lib.rs

### PR DESCRIPTION
**Pull request by humb1t**
Change link to `mockall_double` from broken to working one.

### CODE REVIEW

**Review by asomers — CHANGES_REQUESTED** [review]
Thanks!  Could you please make the commit message a little more useful?  Perhaps something along the lines of "Fix mockall_double documentation link"?

**Comment by humb1t** [comment]
Hi @asomers , because I used github web interface, I can't ammend commit, created a new PR #244

**Comment by asomers** [comment]
Really?  Did the Github web interface choose the PR title "update lib.rs"?  I'm not sure I've ever created a PR entirely through the web interface.

**Comment by humb1t** [comment]
@asomers yes. I usually use web interface to contribute small documentation related changes into oss

**Pull request closed without merging**
